### ISSUE TITLE
Clarification on choosing a reference and SCTransform.

### ISSUE THREAD

**Issue by cnk113** [quon-titative-biology/scAlign#1]
Hello,

I was wondering how the reference set is chosen, is it the first dataset in the list or is it randomly chosen? If it's the latter will there be functionality to choose a reference?
Also is it better to use Seurat's integrated SCTransform on each dataset separately or Normalize, ScaleData, etc? 

Thanks

**Comment by UCDNJJ** [comment]
Hi,

The reference data set is chosen based on the 'reference.data' argument to `scAlignMulti()`. Assuming the list of SCE objects is named before calling `scAlignCreateObject()` then setting reference.data to one of those names will specify the reference set, otherwise all-pairs alignment is performed. 

We haven't tried SCTransform as a normalization method but using the residuals from SCTransform should work as well if not better than the results of ScaleData.

**Comment by cnk113** [comment]
Alright that worked.
Also the tutorials for multiway alignment has an error in it, I believe. When your extracting the common set of variable genes across datasets, and then pull those rows to create the SCE object it throws on out of bounds error. I fixed this by intersecting the union with all genes in all batches.

Thanks.
